server {
    listen 80;
    server_name _;

    client_max_body_size 100m;
    resolver 127.0.0.11 valid=10s ipv6=off;

    location = /health {
        add_header Content-Type application/json;
        return 200 '{"status":"ok","service":"gateway"}';
    }

    location /auth {
        set $auth_upstream http://auth-service:8000;
        proxy_pass $auth_upstream$request_uri;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /users {
        set $user_upstream http://user-service:8000;
        proxy_pass $user_upstream$request_uri;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /courses {
        set $course_upstream http://course-service:8000;
        proxy_pass $course_upstream$request_uri;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /enrollments {
        set $enrollment_upstream http://enrollment-service:8000;
        proxy_pass $enrollment_upstream$request_uri;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /lessons {
        set $lesson_upstream http://lesson-service:8000;
        proxy_pass $lesson_upstream$request_uri;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /progress {
        set $progress_upstream http://progress-service:8000;
        proxy_pass $progress_upstream$request_uri;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /payments {
        set $payment_upstream http://payment-service:8000;
        proxy_pass $payment_upstream$request_uri;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
